In [6]:
import torch

a = torch.randn(4)
b = torch.randn(4)

In [12]:
a = torch.randn(4)
b = torch.randn(4)
torch.dot(a, b)  # Dot product

tensor(0.8724)

In [13]:
a = torch.randn(4, 1)
b = torch.randn(1, 4)
torch.mm(b, a)  # 2d matrix multiplicatioin

tensor([[1.6805]])

In [14]:
b @ a

tensor([[1.6805]])

In [15]:
a = torch.randn(10, 4, 1)
b = torch.randn(10, 1, 4)
torch.bmm(b, a)

tensor([[[ 0.6396]],

        [[-0.1604]],

        [[ 0.7524]],

        [[-1.3822]],

        [[-0.3352]],

        [[-0.8466]],

        [[-2.4400]],

        [[-0.4349]],

        [[ 0.9747]],

        [[ 1.6290]]])