In [1]:
import torch

a = torch.randn(4)
b = torch.randn(4)

In [12]:
a = torch.randn(4)
b = torch.randn(4)
torch.dot(a, b)  # Dot product

tensor(0.8724)

In [13]:
a = torch.randn(4, 1)
b = torch.randn(1, 4)
torch.mm(b, a)  # 2d matrix multiplicatioin

tensor([[1.6805]])

In [14]:
b @ a

tensor([[1.6805]])

In [15]:
a = torch.randn(10, 4, 1)
b = torch.randn(10, 1, 4)
torch.bmm(b, a)

tensor([[[ 0.6396]],

        [[-0.1604]],

        [[ 0.7524]],

        [[-1.3822]],

        [[-0.3352]],

        [[-0.8466]],

        [[-2.4400]],

        [[-0.4349]],

        [[ 0.9747]],

        [[ 1.6290]]])

In [31]:
a = torch.ones(2,4,2,3)
b = torch.ones(2,2,3,2)*2

In [32]:
torch.matmul(a,b).shape

RuntimeError: The size of tensor a (4) must match the size of tensor b (2) at non-singleton dimension 1

In [30]:
torch.matmul(a,b)

tensor([[[[6., 6.],
          [6., 6.]],

         [[6., 6.],
          [6., 6.]]],


        [[[6., 6.],
          [6., 6.]],

         [[6., 6.],
          [6., 6.]]]])

In [10]:
b.shape

torch.Size([3, 1])

In [36]:
b.eq(2)

tensor([[[[True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True]]],


        [[[True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True]]]])

In [37]:
b.data.eq(2)

tensor([[[[True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True]]],


        [[[True, True],
          [True, True],
          [True, True]],

         [[True, True],
          [True, True],
          [True, True]]]])

In [2]:
import torch

a = torch.randn(5,5,512)
b = torch.randn(5,512)

torch.matmul(a,b)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (25x512 and 5x512)

In [3]:
a.shape

torch.Size([5, 5, 512])