In [7]:
import torch
import numpy as np
np.set_printoptions(precision=30)  # Adjust the precision as needed
torch.set_printoptions(precision=30)
# Generate a float32 tensor
float32_tensor = torch.rand(3, 3, dtype=torch.float32)
print("Float32 Tensor:")
print(float32_tensor)  # Convert to NumPy array for better formatting

# Convert to float16
float16_tensor = float32_tensor.to(torch.float16)
print("\nFloat16 Tensor:")
print(float16_tensor)

# Convert to bfloat16
bfloat16_tensor = float32_tensor.to(torch.bfloat16)
print("\nBFloat16 Tensor:")
print(bfloat16_tensor)


Float32 Tensor:
tensor([[0.601156651973724365234375000000, 0.318300247192382812500000000000,
         0.707480013370513916015625000000],
        [0.639416098594665527343750000000, 0.158254563808441162109375000000,
         0.922784507274627685546875000000],
        [0.396492242813110351562500000000, 0.779033362865447998046875000000,
         0.333619594573974609375000000000]])

Float16 Tensor:
tensor([[0.601074218750000000000000000000, 0.318359375000000000000000000000,
         0.707519531250000000000000000000],
        [0.639648437500000000000000000000, 0.158203125000000000000000000000,
         0.922851562500000000000000000000],
        [0.396484375000000000000000000000, 0.778808593750000000000000000000,
         0.333740234375000000000000000000]], dtype=torch.float16)

BFloat16 Tensor:
tensor([[0.601562500000000000000000000000, 0.318359375000000000000000000000,
         0.707031250000000000000000000000],
        [0.640625000000000000000000000000, 0.158203125000000000000000000000,
  

In [8]:
import torch
import numpy as np
np.set_printoptions(precision=30)  # Adjust the precision as needed
torch.set_printoptions(precision=30)
# Generate a float32 tensor
bfloat16_tensor = torch.rand(3, 3, dtype=torch.bfloat16)
print("bfloat16_tensor:")
print(bfloat16_tensor)  # Convert to NumPy array for better formatting

# Convert to float16
float16_tensor = bfloat16_tensor.to(torch.float16)
print("\nFloat16 Tensor:")
print(float16_tensor)

# Convert to bfloat16
float32_tensor = bfloat16_tensor.to(torch.float32)
print("\nfloat32_tensor:")
print(float32_tensor)

bfloat16_tensor:
tensor([[0.734375000000000000000000000000, 0.511718750000000000000000000000,
         0.289062500000000000000000000000],
        [0.984375000000000000000000000000, 0.921875000000000000000000000000,
         0.843750000000000000000000000000],
        [0.292968750000000000000000000000, 0.058593750000000000000000000000,
         0.519531250000000000000000000000]], dtype=torch.bfloat16)

Float16 Tensor:
tensor([[0.734375000000000000000000000000, 0.511718750000000000000000000000,
         0.289062500000000000000000000000],
        [0.984375000000000000000000000000, 0.921875000000000000000000000000,
         0.843750000000000000000000000000],
        [0.292968750000000000000000000000, 0.058593750000000000000000000000,
         0.519531250000000000000000000000]], dtype=torch.float16)

float32_tensor:
tensor([[0.734375000000000000000000000000, 0.511718750000000000000000000000,
         0.289062500000000000000000000000],
        [0.984375000000000000000000000000, 0.921875000000